### ISSUE TITLE
manual pages

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/discuss#10]
With the next **mapview ** release (hopefully not too far away) I am planning to move the mapview repo from [environmentalinformatics-maburg](https://github.com/environmentalinformatics-marburg) to [here](https://github.com/r-spatial). This will also mean that I need to move the online documentation currently hosted at the [github.io repo](https://github.com/environmentalinformatics-marburg/environmentalinformatics-marburg.github.io) over there. My questions are:

1. where's the best place to host manuals for r-spatial? Here or maybe a manual page at [r-spatial.org](http://r-spatial.org/)?
2. if here, how should we organise the [r-spatial web repo](https://github.com/r-spatial/r-spatial.github.io) to host manuals (alongside other things I guess)?
3. do we want to come up with a template for online manuals?

I am not very experienced with html/css stuff, so maybe some of the more web-affine people could provide some thoughts and maybe take the lead on this?

**Comment by pat-s** [comment]
We could use [`pkgdown`](https://github.com/hadley/pkgdown) for each r-spatial package and link selected "articles" at [r-spatial.org](r-spatial.org) in a menu item called "online manuals"?

One could create a special CSS style for all articles at r-spatial.org which everybody can use so that we have some kind of uniqueness. 

(I could also think over moving `sperrorest` to r-spatial.org)

**Comment by tim-salabim** [comment]
I think we do sort of have this under control now using tic (at least for sf and mapview).
