### ISSUE TITLE
RSAGA Issues

### ISSUE THREAD

**Issue by be-marc** [r-spatial/discuss#23]
Hello,

It is not possible to post issues in the RSAGA repo. Could you change the settings?

**Comment by edzer** [comment]
That is because it is a fork; post issues in the original repo here: https://github.com/debangs/RSAGA

**Comment by be-marc** [comment]
Unfortunately, we do not have control over this repo anymore because @debangs does not respond to our e-mails. But it should be possible to activate the issues tab on forks

https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

**Comment by pat-s** [comment]
@edzer we tried to contact debangs for almost a year now over various channels and we couldn't reach him. That's why we used the forked repo in the first place. Even though it's ugly there needs to be a new RSAGA main repo.

So maybe port the fork history into a clean repo and then move to r-spatial.

**Comment by be-marc** [comment]
Okay I created a copy https://github.com/be-marc/RSAGA.

@edzer Could you delete the fork? After that I would transfer the ownership of the new repo to r-spatial

**Comment by edzer** [comment]
Deleted the fork.
