### ISSUE TITLE
A generic web mapping framework

### ISSUE THREAD

**Issue by bhaskarvk** [r-spatial/discuss#4]
There are tons of web mapping options available, just to list out a few

- [Leaflet](http://leafletjs.com/) and it's derivatives (mapbox.js, esri-leaflet, polarmaps)
- [Mapbox-GL](https://www.mapbox.com/mapbox-gl-js/api/)
- [GeoJS](https://github.com/OpenGeoscience/geojs)
- [OpenLayers 3](https://openlayers.org/)
- [Cesium](https://cesiumjs.org/)
- [Arcgis-JS](https://developers.arcgis.com/javascript/) For ESRI users
- [Tangram](https://github.com/tangrams/tangram)
- [MapZen](https://mapzen.com/)

And many many more.

They all share similar concepts. A map element on top of which you can add Tiles, Vector, Raster data, and interactivity using various controls etc.

In theory it should be fairly straight forward to create an htmlwidget with pluggable backend for different JS libs.
This has two advantages
- No need to rewrite R code that does data extraction from sp, sf, geo/topo-JSON, WKT etc.
- Uniform R API for basic functionality regardless of which backend is used.

There are a couple of ways this can be done. 

### Approach 1: 
Build a htmlwdiget with pluggable backend and one ref. implementation (e.g. leaflet) and add more and more backends as package progresses.

### Approach 2:
Have an R package with just the R API, and implement each backend in a dedicated package.

For now I am not proposing anything, but just putting my thoughts down and hoping to get some response/comments from the community. The whole idea is to provide many flexible GeoViz options to the users and yet do so with a consistent R API.

**Comment by barryrowlingson** [comment]
Or use a proven and capable mapping system (QGIS) and build an R package to communicate between it and either a running QGIS or a standalone QGIS Map Canvas with all the styling and layering tools.

I've prototyped something a bit like that, but: it relies on rPython (which doesn't run on Windows) to run a QGIS map canvas; it runs in the same thread as R so is inactive unless a certain function is running in R; and it crashed quite a bit. But it was great to be able to add layers to a QGIS map with a tiled openstreetmap background and style the layer with QGIS cartographic power seamlessly, from R, like it was an R graphics window.

I have considered whether completing this and addressing the flaws would make a good GSoC project for this year, either under the OSGEO or R umbrellas.

I don't think any of the JS mapping engines have the power or interface of QGIS map canvas.

**Comment by tim-salabim** [comment]
Or apply for an RConsortium grant for the QGIS map canvas bridge.

**Comment by bhaskarvk** [comment]
@barryrowlingson I would like to know more about the statement 

`I don't think any of the JS mapping engines have the power or interface of QGIS map canvas.`

Not that I am disputing it, but knowing where JS mapping falls short will go a long way in addressing those concerns. Besides exploratory analysis of GIS data, there's another use case, that of presenting GeoSpatial data for end-user consumption. I think that's where the JS mapping really shines, as it takes advantage of the already available protocols that work on the Internet.

**Comment by mdsumner** [comment]
@barryrowlingson The JS mapping engines allows us to transcend the simple features model in ways that aren't readily available to QGIS. 

QGIS geometry generators also allows that, but it's not clear how general that is or whether it's the best way to go.

**Comment by barryrowlingson** [comment]
Apologies for side-tracking somewhat, here's my considered thought on the original question, which was do we need a generic web-mapping framework with a choice of backed "drivers" (eg leaflet, OpenLayers) for generating web maps.
 
Short Answer: No. 

Slightly Longer Answer: it might be nice, but I don't think its worth the effort

Reasoning: An interface for quickly making interactive web-based maps from R spatial data is a great thing. We have that (in several guises) already, and we can plot shapes and tiles and rasters in controllable styles (colours, line widths etc) using leaflet. Why would we need to use, say, Cesium? Because you need some feature of Cesium that isn't in Leaflet? Like setting an initial altitude of the eye point? You're now at the point where you need Cesium-specific, not web-map generic, functionality. And that is probably the point where your time would be better spent writing the whole thing in Javascript and just using R to create the spatial data for it (geoJSON, most likely). Similar argument applies for OpenLayers or any of the other JS framworks.

So simple users just want a web map and don't care that the backend is leaflet, and advanced users are crafting their own javascript. How many middling users are there that might want to switch from leaflet to OpenLayers? I don't think it justifies the effort. We have a database-independent infrastructure (DBI) because the type of database is often imposed on us externally, so an abstraction level is useful. For web maps, if there is an external imposition then the chances are you will be having to craft javascript to deal with it anyway.
